spring.application.name=api-gateway

server.port=9000

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webmvc.routes[0].id=identity-service

spring.cloud.gateway.server.webmvc.routes[0].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/identity/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webmvc.routes[1].id=assessment-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ASSESSMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/assessment/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api/assessment/(?<segment>.*), /api/$\{segment}

# ===============================
# Course Service
# ===============================

spring.cloud.gateway.server.webmvc.routes[2].id=course-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://COURSE-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/course/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=2