spring.application.name=api-gateway

server.port=${PORT:9000}

# Eureka Server (used only locally; on Render routes use direct URLs below)
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.cloud.gateway.server.webmvc.routes[0].id=identity-service

spring.cloud.gateway.server.webmvc.routes[0].uri=${IDENTITY_SERVICE_URL:https://lms-identity-service.onrender.com}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/identity/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webmvc.routes[1].id=assessment-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${ASSESSMENT_SERVICE_URL:https://lms-assessment-service.onrender.com}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/assessment/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api/assessment/(?<segment>.*), /api/$\{segment}

# ===============================
# Course Service
# ===============================

spring.cloud.gateway.server.webmvc.routes[2].id=course-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${COURSE_SERVICE_URL:https://lms-course-service.onrender.com}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/course/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=2