spring.application.name=api-gateway

server.port=9000

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webmvc.routes[0].id=identity-service

spring.cloud.gateway.server.webmvc.routes[0].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/identity/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=2

# CORS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.server.webmvc.globalcors.add-to-simple-url-handler-mapping=true