spring.application.name=course-service


server.port=8083

server.tomcat.accesslog.enabled=true
# ===============================
# MySQL Database
# ===============================

spring.datasource.url=jdbc:postgresql://dpg-daif44bm8hqs73cjqkdg-a.oregon-postgres.render.com/lms_db_ak0i
spring.datasource.username=lms_db_ak0i_user
spring.datasource.password=JNOrJkUF380lFjlx8v8lAOZsLbqw82hY


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Eureka Client
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=your-very-long-secret-key-change-this-later
jwt.expiration=86400000
