spring.application.name=identity-service

server.port=8081
server.tomcat.accesslog.enabled=true

# MySQL - Identity Service database
spring.datasource.url=jdbc:postgresql://dpg-daif44bm8hqs73cjqkdg-a.oregon-postgres.render.com/lms_db_ak0i
spring.datasource.username=lms_db_ak0i_user
spring.datasource.password=JNOrJkUF380lFjlx8v8lAOZsLbqw82hY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=your-very-long-secret-key-change-this-later
jwt.expiration=86400000

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true